{{-- PWA head tags, shared by every installable surface (admin/POS, portal,
     customer display, storefront, login).

     The manifest itself is generated by PwaManifestController from
     System Settings → PWA; only the surface-specific bits are passed in here:

       $manifest   - manifest URL for this surface (default: the admin one)
       $themeColor - browser UI color (default: the configured PWA theme color)
       $appTitle   - iOS home-screen label (default: the configured PWA name)
       $statusBar  - apple-mobile-web-app-status-bar-style (default: "default")

     Nothing is emitted when the PWA is switched off, which is what stops the
     browser offering to install the app. --}}
@php
    $pwaSetting = $app_settings ?? null;
    // The column is absent on installs that have not run the PWA migration —
    // treat that as enabled so the app keeps behaving as it did before.
    $pwaOn = (bool) ($pwaSetting->pwa_enabled ?? true);
    $pwaName = trim((string) ($pwaSetting->pwa_name ?? '')) ?: ($pwaSetting->app_name ?? 'Stocky');
    $pwaTheme = trim((string) ($pwaSetting->pwa_theme_color ?? '')) ?: '#2f3640';
    // @include leaks every parent-view variable in here, so a layout defining
    // its own $manifest (e.g. a decoded asset manifest array) must not be
    // mistaken for our manifest URL.
    $pwaManifestUrl = isset($manifest) && is_string($manifest) ? $manifest : '/manifest.webmanifest';
@endphp
{{-- Read by bundled front-ends that register the service worker themselves
     (the storefront), so switching the PWA off applies to them too. --}}
<script>window.__PWA_ENABLED__ = @json($pwaOn);</script>
@if ($pwaOn)
    <link rel="manifest" href="{{ $pwaManifestUrl }}">
    <meta name="theme-color" content="{{ $themeColor ?? $pwaTheme }}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="{{ $statusBar ?? 'default' }}">
    <meta name="apple-mobile-web-app-title" content="{{ $appTitle ?? $pwaName }}">
    <link rel="apple-touch-icon" href="/pwa_images/pwa-icon-192.png">
@endif
