/**
 * Per-item sidebar icons — the exact <lucide-icon name="..."> values from the
 * legacy Vue 2 largeSidebar/sidebar.vue, keyed by the /app path (the `to` on
 * each menu entry). Used by the default and flat sidebars so every submenu row
 * shows the same icon it had in the old app.
 *
 * Regenerate from that sidebar if items change; kebab names map to
 * lucide-vue-next PascalCase components.
 */
import {
    AlarmClock, Archive, ArrowUpCircle, Atom, Banknote, BarChart, BarChart3, Barcode, BellRing, Book, Bookmark, BriefcaseBusiness, Bug, Building, Calculator, Calendar, CalendarCheck, CalendarDays, Camera, Check, CheckCheck, ChevronLeft, ChevronRight, ClipboardList, Clock, Cloud, Copy, CornerUpLeft, CreditCard, Database, DatabaseBackup, DatabaseZap, DollarSign, Download, FilePlus, FileText, Files, Folder, HeartPulse, History, IdCard, Key, Layers, LayoutDashboard, Library, Lightbulb, List, Lock, Mail, MapPin, Megaphone, Menu, MessageCircle, MessageSquare, MonitorUp, Package, Pencil, PieChart, Plus, Quote, Receipt, ReceiptText, Ruler, ScanBarcode, Settings, Shield, ShieldCheck, ShoppingBasket, ShoppingCart, Star, Store, Tag, Ticket, TrendingUp, Trophy, User, UserMinus, Users, Wallet, Warehouse, Wrench, Zap,
    // Manual additions for reports that don't exist in the legacy reference sidebar:
    ArrowLeftRight, Award, CalendarClock, FilePen, ListChecks, PackageX, Percent, SlidersHorizontal, TrendingDown, Truck,
    // Manual additions for other items not in the reference sidebar:
    ChefHat, CircleDollarSign, Gift, PackageCheck,
    // Fleet module — without these, every row under Fleet Management inherits
    // the group's truck icon and the six items look identical.
    // (LayoutDashboard, Wrench and BarChart3 are already imported above.)
    Car, Fuel, UserCheck,
    // Hospital module — one glyph per row, so the eight entries under
    // Hospital do not all inherit the module's heart icon.
    Stethoscope, BedDouble, FlaskConical, TestTubes, ClipboardPlus, ReceiptText as HmsBilling,
    // School module — one glyph per row, so the entries under School do not
    // all inherit the module's graduation-cap icon.
    School as SchoolIcon, BookOpenCheck, CalendarRange, Wallet as SchoolFees, UserSquare,
    // Projects Management — one glyph per row rather than the group's icon.
    KanbanSquare, Flag, Timer,
    // Asset Management (UserCheck, ArrowLeftRight and TrendingDown are already imported above).
    Hammer,
    // Shopify (LayoutDashboard and Store are already imported above).
    RefreshCcw, Link2, ScrollText,
    // Manufacturing MRP (LayoutDashboard, BarChart3, Wrench, ShieldCheck and
    // Calculator are already imported above).
    Factory, FileStack, Cog,
} from 'lucide-vue-next';

export const MENU_ITEM_ICONS = {
    "/app/dashboard": BarChart,
    "/app/sale_return/list": ChevronRight,
    "/app/purchase_return/list": ChevronLeft,
    "/app/subscription_product/list": DollarSign,
    "/app/projects": Archive,
    "/app/contracts": ClipboardList,
    "/app/tasks": Check,
    "/app/woocommerce": ShoppingCart,
    "/app/knowledge-base": Book,
    "/app/knowledge-base/groups": Folder,
    "/app/reports/ai_reports": Lightbulb,
    "/app/Store/Settings": Settings,
    "/app/Store/PaymentGateway": CreditCard,
    "/app/Store/Orders": Receipt,
    "/app/Store/Collections": Check,
    "/app/Store/Banners": Wallet,
    "/app/Store/Subscribers": Users,
    "/app/Store/Messages": MessageSquare,
    "/app/Store/InviteCodes": Ticket,
    "/app/Store/PendingCustomers": Clock,
    "/app/Store/ShippingMethods": Package,
    "/app/Store/TaxRates": Calculator,
    "/app/Store/Coupons": Tag,
    "/app/Store/FlashSales": Zap,
    "/app/Store/Reviews": Star,
    "/app/Store/Popups": Megaphone,
    "/app/Store/QuoteRequests": Quote,
    "/app/Store/Returns": CornerUpLeft,
    "/app/Store/Pages": FileText,
    "/app/Store/Menus": Menu,
    "/app/realestate/properties": Building,
    "/app/realestate/categories": Tag,
    "/app/realestate/inquiries": Mail,
    "/app/EWallet/Dashboard": LayoutDashboard,
    "/app/EWallet/Items": CreditCard,
    "/app/EWallet/Settings": Settings,
    "/app/products/store": FilePlus,
    "/app/products/list": Files,
    "/app/products/import": Download,
    "/app/products/import-update": Pencil,
    "/app/products/opening_stock_import": FilePlus,
    "/app/products/barcode": Barcode,
    "/app/products/count_stock": CheckCheck,
    "/app/products/Categories": Copy,
    "/app/products/SubCategories": Library,
    "/app/products/Brands": Bookmark,
    "/app/products/SizeGuides": Ruler,
    "/app/products/Units": Quote,
    "/app/products/Batches": HeartPulse,
    "/app/serial_numbers/list": ScanBarcode,
    "/app/accounting-v2/dashboard": TrendingUp,
    "/app/accounting-v2/chart-of-accounts": Database,
    "/app/accounting-v2/journal-entries": Files,
    "/app/accounting-v2/reports/trial-balance": TrendingUp,
    "/app/accounting-v2/reports/profit-and-loss": Wallet,
    "/app/accounting-v2/reports/balance-sheet": PieChart,
    "/app/accounting-v2/reports/tax-report": Files,
    "/app/adjustments/store": FilePlus,
    "/app/adjustments/list": Files,
    "/app/transfers/store": FilePlus,
    "/app/transfers/list": Files,
    "/app/damages/store": FilePlus,
    "/app/damages/list": Files,
    "/app/accounts": Files,
    "/app/transfer_money": Files,
    "/app/expenses/store": FilePlus,
    "/app/expenses/list": Files,
    "/app/deposits/store": FilePlus,
    "/app/deposits/list": Files,
    "/app/expenses/category": Files,
    "/app/deposits/category": Files,
    "/app/purchases/store": FilePlus,
    "/app/purchases/list": Files,
    "/app/purchases/import_purchases": FilePlus,
    "/app/service/jobs": Files,
    "/app/service/technicians": Files,
    "/app/service/checklist-categories": Folder,
    "/app/service/checklists": Check,
    "/app/service/history": CalendarDays,
    "/app/assets/store": FilePlus,
    "/app/assets/list": Files,
    "/app/assets/due": Clock,
    "/app/assets/category": Folder,
    "/app/sales/store": FilePlus,
    "/app/sales/import_sales": FilePlus,
    "/app/sales/list": Files,
    "/app/promotions": Percent,
    "/app/pos": Files,
    "/app/customer-display/setup": Barcode,
    "/app/sales/shipment": Files,
    "/app/real-time-sales-counter": ShoppingCart,
    "/app/bookings/list": Files,
    "/app/bookings/calendar": CalendarDays,
    "/app/bookings/trays": Layers,
    "/app/commissions/programs": Files,
    "/app/commissions/agents": Users,
    "/app/commissions/rules": Settings,
    "/app/commissions/receipts": Receipt,
    "/app/commissions/report": TrendingUp,
    "/app/quotations/store": FilePlus,
    "/app/quotations/list": Files,
    "/app/hrm/company": BriefcaseBusiness,
    "/app/hrm/departments": Store,
    "/app/hrm/designations": Camera,
    "/app/hrm/office_Shift": Clock,
    "/app/hrm/employees": Wrench,
    "/app/hrm/attendance": Clock,
    "/app/hrm/leaves/list": IdCard,
    "/app/hrm/leaves/type": IdCard,
    "/app/hrm/holidays": BellRing,
    "/app/hrm/payrolls": Banknote,
    "/app/recruit/dashboard": LayoutDashboard,
    "/app/recruit/jobs": BriefcaseBusiness,
    "/app/recruit/candidates": User,
    "/app/recruit/applications": FileText,
    "/app/recruit/interviews": Calendar,
    "/app/recruit/categories": List,
    "/app/recruit/reports": BarChart3,
    "/app/meeting/dashboard": LayoutDashboard,
    "/app/meeting/meetings": CalendarCheck,
    "/app/meeting/calendar": Calendar,
    "/app/meeting/reports": BarChart3,
    "/app/marketing/dashboard": LayoutDashboard,
    "/app/marketing/campaigns": Megaphone,
    "/app/marketing/segments": Users,
    "/app/marketing/templates/sms": MessageSquare,
    "/app/marketing/templates/whatsapp": MessageCircle,
    "/app/marketing/templates/email": Mail,
    "/app/marketing/reports": BarChart3,
    "/app/marketing/settings": Settings,
    "/app/People/Customers": ShieldCheck,
    "/app/People/Customers/create": Plus,
    "/app/People/Customers_import": Download,
    "/app/People/Customers_without_ecommerce": ShieldCheck,
    "/app/People/Customers_ecommerce": ShieldCheck,
    "/app/People/Suppliers": ShieldCheck,
    "/app/People/Suppliers/create": Plus,
    "/app/People/Suppliers_import": Download,
    "/app/User_Management/Users": ShieldCheck,
    "/app/User_Management/permissions": Key,
    "/app/settings/System_settings": Settings,
    "/app/settings/quickbooks_sync": Banknote,
    "/app/settings/appearance_settings": DatabaseZap,
    "/app/settings/translations_settings": DatabaseZap,
    "/app/settings/payment_methods": Banknote,
    "/app/settings/sms_settings": MessageSquare,
    "/app/settings/sms_templates": MessageSquare,
    "/app/settings/mail_settings": Mail,
    "/app/settings/email_templates": Mail,
    "/app/settings/pos_settings": DatabaseZap,
    "/app/settings/pos_receipt": Calculator,
    "/app/settings/module_settings": DatabaseZap,
    "/app/settings/business_modules": Layers,
    "/app/settings/update_settings": ArrowUpCircle,
    "/app/settings/payment_gateway": Banknote,
    "/app/settings/Warehouses": Store,
    "/app/settings/Warehouse_Locations": MapPin,
    "/app/settings/Currencies": DollarSign,
    "/app/settings/Backup": DatabaseBackup,
    "/app/settings/system_health": MonitorUp,
    "/app/settings/webhooks": Cloud,
    "/app/settings/login_devices": Lock,
    "/app/reports/sales-3d-dashboard": Atom,
    "/app/reports/payments_purchase": IdCard,
    "/app/reports/payments_sale": IdCard,
    "/app/reports/payments_sales_returns": IdCard,
    "/app/reports/payments_purchases_returns": IdCard,
    "/app/reports/report_transactions": DollarSign,
    "/app/reports/cash_flow_report": TrendingUp,
    "/app/reports/seller_report": User,
    "/app/reports/profit_and_loss": Wallet,
    "/app/reports/profit/product": Package,
    "/app/reports/profit/category": Tag,
    "/app/reports/profit/unit": Ruler,
    "/app/reports/profit/customer": Users,
    "/app/reports/profit/date": CalendarDays,
    "/app/reports/profit/warehouse": Warehouse,
    "/app/reports/analytics_report": BarChart,
    "/app/reports/stock_inventory_valuation": TrendingUp,
    "/app/reports/inventory_valuation_summary": PieChart,
    "/app/reports/expenses_report": ReceiptText,
    "/app/reports/deposits_report": Shield,
    "/app/reports/quantity_alerts": AlarmClock,
    "/app/reports/warehouse_report": Warehouse,
    "/app/reports/internal_location_report": MapPin,
    "/app/reports/stock_report": TrendingUp,
    "/app/reports/serial_available_report": ScanBarcode,
    "/app/reports/serial_sold_report": ScanBarcode,
    "/app/reports/serial_movement_report": History,
    "/app/reports/serial_inventory_report": Layers,
    "/app/reports/negative_stock_report": TrendingUp,
    "/app/reports/product_report": Barcode,
    "/app/reports/return_ratio_report": TrendingUp,
    "/app/reports/sales_report": BarChart,
    "/app/reports/product_sales_report": TrendingUp,
    "/app/reports/report_sales_by_category": Tag,
    "/app/reports/report_sales_by_brand": Store,
    "/app/reports/purchase_report": ShoppingCart,
    "/app/reports/product_purchases_report": ShoppingBasket,
    "/app/reports/customers_report": User,
    "/app/reports/inactive_customers": UserMinus,
    "/app/reports/providers_report": User,
    "/app/reports/top_selling_products": Trophy,
    "/app/reports/top_customers": Trophy,
    "/app/reports/users_report": User,
    "/app/reports/login_activity_report": Lock,
    "/app/reports/report_error_logs": Bug,
    // Reports not present in the legacy reference sidebar — distinct icons so
    // they don't all fall back to the Reports module icon (trending-up).
    "/app/reports/attendance_report": CalendarCheck,
    "/app/reports/cash-registers": Calculator,
    "/app/reports/warranty_guarantee_report": ShieldCheck,
    "/app/reports/zero_sales_products_report": TrendingDown,
    "/app/reports/dead_stock_report": PackageX,
    "/app/reports/expiry_report": CalendarClock,
    "/app/reports/batch_register_report": Layers,
    "/app/reports/stock_aging_report": History,
    "/app/reports/stock_transfer_report": ArrowLeftRight,
    "/app/reports/stock_adjustment_report": SlidersHorizontal,
    "/app/reports/discount_summary_report": Percent,
    "/app/reports/customer_loyalty_points_report": Award,
    "/app/reports/tax_summary_report": ReceiptText,
    "/app/reports/draft_invoices_report": FilePen,
    "/app/reports/top_suppliers_report": Truck,
    "/app/reports/service_jobs_report": Wrench,
    "/app/reports/checklist_completion_report": ListChecks,
    "/app/reports/customer_maintenance_history_report": ClipboardList,
    // Non-report items missing from the reference sidebar.
    "/app/kitchen-display": ChefHat,
    "/app/service/jobs?status=quoted": Clock,
    "/app/service/jobs?status=ready": PackageCheck,
    "/app/service/jobs?payment_status=unpaid": CircleDollarSign,
    "/app/loyalty/rewards": Gift,

    // Vehicle & Fleet Management
    "/app/fleet/dashboard": LayoutDashboard,
    "/app/fleet/vehicles": Car,
    "/app/fleet/maintenance": Wrench,
    "/app/fleet/fuel-logs": Fuel,
    "/app/fleet/assignments": UserCheck,
    "/app/fleet/reports": BarChart3,

    // Hospital Management
    "/app/hospital/dashboard": LayoutDashboard,
    "/app/hospital/patients": Users,
    "/app/hospital/doctors": Stethoscope,
    "/app/hospital/departments": Building,
    "/app/hospital/appointments": CalendarCheck,
    "/app/hospital/visits": ClipboardPlus,
    "/app/hospital/wards": BedDouble,
    "/app/hospital/admissions": BedDouble,
    "/app/hospital/lab-tests": TestTubes,
    "/app/hospital/lab-orders": FlaskConical,
    "/app/hospital/invoices": HmsBilling,
    "/app/hospital/reports": BarChart3,

    // School Management
    "/app/school/dashboard": LayoutDashboard,
    "/app/school/students": Users,
    "/app/school/enrollments": UserSquare,
    "/app/school/teachers": SchoolIcon,
    "/app/school/academics": Library,
    "/app/school/attendance": CheckCheck,
    "/app/school/timetable": CalendarRange,
    "/app/school/exams": BookOpenCheck,
    "/app/school/fees": SchoolFees,
    "/app/school/reports": BarChart3,

    // Projects Management
    "/app/projects/dashboard": LayoutDashboard,
    "/app/projects": Archive,
    "/app/tasks": Check,
    "/app/tasks/board": KanbanSquare,
    "/app/projects/milestones": Flag,
    "/app/projects/timesheets": Timer,
    "/app/projects/reports": BarChart3,

    // Asset Management
    "/app/assets/dashboard": LayoutDashboard,
    "/app/assets/assignments": UserCheck,
    "/app/assets/maintenance": Hammer,
    "/app/assets/transfers": ArrowLeftRight,
    "/app/assets/depreciation": TrendingDown,
    "/app/assets/reports": BarChart3,

    // Shopify Integration
    "/app/shopify/dashboard": LayoutDashboard,
    "/app/shopify/stores": Store,
    "/app/shopify/sync": RefreshCcw,
    "/app/shopify/mappings": Link2,
    "/app/shopify/logs": ScrollText,

    // Advanced Manufacturing MRP
    "/app/mrp/dashboard": LayoutDashboard,
    "/app/mrp/production-orders": Factory,
    "/app/mrp/work-orders": Wrench,
    "/app/mrp/boms": FileStack,
    "/app/mrp/work-centers": Cog,
    "/app/mrp/quality": ShieldCheck,
    "/app/mrp/planning": Calculator,
    "/app/mrp/reports": BarChart3,
};
