/**
 * Navigation for the whole admin — generated from the legacy Sidebar.vue,
 * so labels (i18n keys), routes, icons and permission gates match it exactly.
 * Three levels are supported: group > sub-group > item (e.g. Reports > Payments > Sales).
 *
 * Every module is listed, migrated or not. resolveTarget() sends each entry to
 * the Vue 3 page when it exists (MIGRATED_ROUTES) and otherwise deep-links back
 * into the legacy SPA — so users get ONE navigation surface for the whole
 * migration. As a page is migrated, add its legacy path to MIGRATED_ROUTES.
 *
 * Labels are translation keys (flat, legacy style — spaces allowed); every
 * label has an entry in database/seeders/translations/en.php.
 * `permissions` = show when the user has ANY of them ([] = always visible).
 */

// legacy SPA path -> path in this app
export const MIGRATED_ROUTES = {
    '/app/dashboard': '/dashboard',
    '/app/products/store': '/products/create',
    '/app/products/list': '/products',
    '/app/products/count_stock': '/products/count-stock',
    '/app/products/Batches': '/products/batches',
    '/app/serial_numbers/list': '/serial-numbers',
    '/app/products/Brands': '/brands',
    '/app/products/vehicle_fitment': '/products/vehicle-fitment',
    '/app/products/Categories': '/categories',
    '/app/products/SubCategories': '/subcategories',
    '/app/products/Units': '/units',
    '/app/products/SizeGuides': '/size-guides',
    '/app/settings/Currencies': '/currencies',
    '/app/settings/Warehouses': '/warehouses',
    '/app/settings/payment_methods': '/settings/payment-methods',
    // Rack locations merged into the Warehouses page (tab).
    '/app/settings/Warehouse_Locations': '/warehouses',
    '/app/settings/payment_gateway': '/settings/payment-gateway',
    '/app/settings/mail_settings': '/settings/mail',
    '/app/settings/login_devices': '/settings/login-devices',
    '/app/settings/system_health': '/settings/system-health',
    '/app/settings/sms_templates': '/settings/sms-templates',
    '/app/settings/email_templates': '/settings/email-templates',
    '/app/settings/Backup': '/settings/backup',
    '/app/settings/pos_settings': '/settings/pos',
    '/app/settings/appearance_settings': '/settings/appearance',
    '/app/settings/sms_settings': '/settings/sms',
    '/app/settings/translations_settings': '/settings/languages',
    '/app/settings/webhooks': '/settings/webhooks',
    '/app/kitchen-display': '/kitchen-display',
    '/app/bookings/list': '/bookings',
    '/app/reports/dead_stock_report': '/reports/dead-stock',
    '/app/reports/zero_sales_products_report': '/reports/zero-sales',
    '/app/reports/negative_stock_report': '/reports/negative-stock',
    '/app/reports/expiry_report': '/reports/expiry',
    '/app/reports/discount_summary_report': '/reports/discount-summary',
    '/app/reports/tax_summary_report': '/reports/tax-summary',
    '/app/reports/customer_loyalty_points_report': '/reports/loyalty-points',
    '/app/reports/inactive_customers': '/reports/inactive-customers',
    '/app/reports/draft_invoices_report': '/reports/draft-invoices',
    '/app/reports/top_suppliers_report': '/reports/top-suppliers',
    '/app/reports/warranty_guarantee_report': '/reports/warranty',
    '/app/reports/stock_adjustment_report': '/reports/stock-adjustment',
    '/app/reports/serial_sold_report': '/reports/serial-sold',
    '/app/reports/serial_available_report': '/reports/serial-available',
    '/app/reports/serial_movement_report': '/reports/serial-movement',
    '/app/reports/serial_inventory_report': '/reports/serial-inventory',
    '/app/reports/batch_register_report': '/reports/batch-register',
    '/app/reports/payments_sale': '/reports/payments-sale',
    '/app/reports/payments_purchase': '/reports/payments-purchase',
    '/app/reports/payments_sales_returns': '/reports/payments-sales-returns',
    '/app/reports/payments_purchases_returns': '/reports/payments-purchases-returns',
    '/app/reports/customers_report': '/reports/customers',
    '/app/reports/providers_report': '/reports/suppliers',
    '/app/reports/cash-registers': '/reports/cash-registers',
    '/app/reports/attendance_report': '/reports/attendance',
    '/app/reports/service_jobs_report': '/reports/service-jobs',
    '/app/reports/checklist_completion_report': '/reports/checklist-completion',
    '/app/reports/customer_maintenance_history_report': '/reports/maintenance-history',
    '/app/reports/users_report': '/reports/users',
    '/app/reports/login_activity_report': '/reports/login-activity',
    '/app/reports/report_error_logs': '/reports/error-logs',
    '/app/reports/top_selling_products': '/reports/top-selling-products',
    '/app/reports/top_customers': '/reports/top-customers',
    '/app/reports/expenses_report': '/reports/expenses',
    '/app/reports/deposits_report': '/reports/deposits',
    '/app/reports/sales_report': '/reports/sales',
    '/app/reports/purchase_report': '/reports/purchases',
    '/app/reports/quantity_alerts': '/reports/quantity-alerts',
    '/app/reports/stock_report': '/reports/stock',
    '/app/reports/product_report': '/reports/product',
    '/app/reports/product_sales_report': '/reports/product-sales',
    '/app/reports/product_purchases_report': '/reports/product-purchases',
    '/app/reports/seller_report': '/reports/seller',
    '/app/reports/report_transactions': '/reports/transactions',
    '/app/reports/internal_location_report': '/reports/internal-location',
    '/app/reports/report_sales_by_category': '/reports/sales-by-category',
    '/app/reports/report_sales_by_brand': '/reports/sales-by-brand',
    '/app/reports/profit_and_loss': '/reports/profit-and-loss',
    '/app/reports/cash_flow_report': '/reports/cash-flow',
    '/app/reports/stock_transfer_report': '/reports/stock-transfer',
    '/app/reports/return_ratio_report': '/reports/return-ratio',
    '/app/reports/stock_aging_report': '/reports/stock-aging',
    '/app/reports/inventory_valuation_summary': '/reports/inventory-valuation-summary',
    '/app/reports/stock_inventory_valuation': '/reports/stock-inventory-valuation',
    '/app/reports/warehouse_report': '/reports/warehouse',
    '/app/People/Customers': '/customers',
    '/app/People/Customers/create': '/customers/create',
    '/app/People/Customers_import': '/customers/import',
    '/app/People/Suppliers': '/suppliers',
    '/app/People/Suppliers/create': '/suppliers/create',
    '/app/People/Suppliers_import': '/suppliers/import',
    '/app/products/import': '/products/import',
    '/app/products/import-update': '/products/import-update',
    '/app/products/opening_stock_import': '/products/opening-stock-import',
    '/app/products/barcode': '/products/barcode',
    '/app/accounts': '/accounts',
    '/app/transfer_money': '/transfer-money',
    '/app/expenses/list': '/expenses',
    '/app/expenses/store': '/expenses/create',
    '/app/expenses/category': '/expenses/categories',
    '/app/damages/list': '/damages',
    '/app/damages/store': '/damages/create',
    '/app/sales/shipment': '/shipments',
    '/app/People/Customers_without_ecommerce': '/customers-without-login',
    '/app/People/Customers_ecommerce': '/customers-with-login',
    '/app/loyalty/rewards': '/loyalty/rewards',
    '/app/real-time-sales-counter': '/real-time-sales-counter',
    '/app/customer-display/setup': '/customer-display/setup',
    '/app/settings/pos_receipt': '/settings/pos-receipt',
    '/app/settings/module_settings': '/settings/modules',
    '/app/settings/business_modules': '/settings/business-modules',
    '/app/settings/update_settings': '/settings/update',
    '/app/settings/System_settings': '/settings/system',
    '/app/settings/quickbooks_sync': '/settings/quickbooks',
    '/app/woocommerce': '/woocommerce',
    '/app/shopify/dashboard': '/shopify',
    '/app/shopify/stores': '/shopify/stores',
    '/app/shopify/sync': '/shopify/sync',
    '/app/shopify/mappings': '/shopify/mappings',
    '/app/shopify/logs': '/shopify/logs',
    '/app/mrp/dashboard': '/mrp',
    '/app/mrp/production-orders': '/mrp/production-orders',
    '/app/mrp/work-orders': '/mrp/work-orders',
    '/app/mrp/boms': '/mrp/boms',
    '/app/mrp/work-centers': '/mrp/work-centers',
    '/app/mrp/quality': '/mrp/quality',
    '/app/mrp/planning': '/mrp/planning',
    '/app/mrp/reports': '/mrp/reports',
    '/app/assets/due': '/assets/due',
    '/app/subscription_product/list': '/subscriptions',
    '/app/bookings/calendar': '/bookings/calendar',
    '/app/service/jobs': '/service/jobs',
    '/app/service/jobs?status=quoted': '/service/jobs?status=quoted',
    '/app/service/jobs?status=ready': '/service/jobs?status=ready',
    '/app/service/jobs?payment_status=unpaid': '/service/jobs?payment_status=unpaid',
    '/app/service/technicians': '/service/technicians',
    '/app/service/checklist-categories': '/service/checklist-categories',
    '/app/service/checklists': '/service/checklists',
    '/app/service/history': '/service/history',
    '/app/User_Management/permissions': '/permissions',
    '/app/Store/Settings': '/store/settings',
    '/app/Store/PaymentGateway': '/store/payment-gateway',
    '/app/Store/Orders': '/store/orders',
    '/app/Store/Collections': '/store/collections',
    '/app/Store/Messages': '/store/messages',
    '/app/Store/InviteCodes': '/store/invite-codes',
    '/app/Store/FlashSales': '/store/flash-sales',
    '/app/Store/Subscribers': '/store/subscribers',
    '/app/Store/QuoteRequests': '/store/quote-requests',
    '/app/Store/Reviews': '/store/reviews',
    '/app/Store/Returns': '/store/returns',
    '/app/Store/Menus': '/store/menus',
    '/app/Store/Coupons': '/store/coupons',
    '/app/Store/TaxRates': '/store/tax-rates',
    '/app/Store/PendingCustomers': '/store/pending-customers',
    '/app/Store/Pages': '/store/pages',
    '/app/Store/Popups': '/store/popups',
    '/app/Store/ShippingMethods': '/store/shipping-methods',
    '/app/Store/Banners': '/store/banners',
    '/app/realestate/properties': '/realestate/properties',
    '/app/realestate/categories': '/realestate/categories',
    '/app/realestate/inquiries': '/realestate/inquiries',
    '/app/reports/ai_reports': '/reports/ai-reports',
    '/app/reports/profit/product': '/reports/profit/product',
    '/app/reports/profit/category': '/reports/profit/category',
    '/app/reports/profit/unit': '/reports/profit/unit',
    '/app/reports/profit/customer': '/reports/profit/customer',
    '/app/reports/profit/date': '/reports/profit/date',
    '/app/reports/profit/warehouse': '/reports/profit/warehouse',
    '/app/reports/sales-3d-dashboard': '/reports/sales-3d-dashboard',
    '/app/accounting-v2/dashboard': '/accounting-v2/dashboard',
    '/app/accounting-v2/chart-of-accounts': '/accounting-v2/chart-of-accounts',
    '/app/accounting-v2/journal-entries': '/accounting-v2/journal-entries',
    '/app/accounting-v2/reports/trial-balance': '/accounting-v2/reports/trial-balance',
    '/app/accounting-v2/reports/profit-and-loss': '/accounting-v2/reports/profit-and-loss',
    '/app/accounting-v2/reports/balance-sheet': '/accounting-v2/reports/balance-sheet',
    '/app/accounting-v2/reports/tax-report': '/accounting-v2/reports/tax-report',
    '/app/meeting/dashboard': '/meeting/dashboard',
    '/app/meeting/calendar': '/meeting/calendar',
    '/app/meeting/reports': '/meeting/reports',
    '/app/EWallet/Dashboard': '/ewallet/dashboard',
    '/app/EWallet/Items': '/ewallet/items',
    '/app/EWallet/Settings': '/ewallet/settings',
    '/app/recruit/dashboard': '/recruit/dashboard',
    '/app/recruit/jobs': '/recruit/jobs',
    '/app/recruit/categories': '/recruit/categories',
    '/app/recruit/candidates': '/recruit/candidates',
    '/app/recruit/applications': '/recruit/applications',
    '/app/recruit/interviews': '/recruit/interviews',
    '/app/recruit/reports': '/recruit/reports',
    '/app/commissions/programs': '/commissions/programs',
    '/app/commissions/agents': '/commissions/agents',
    '/app/commissions/rules': '/commissions/rules',
    '/app/commissions/receipts': '/commissions/receipts',
    '/app/commissions/report': '/commissions/report',
    '/app/purchases/import_purchases': '/purchases/import',
    '/app/sales/import_sales': '/sales/import',
    '/app/User_Management/Users': '/users',
    '/app/hrm/company': '/hrm/companies',
    '/app/hrm/departments': '/hrm/departments',
    '/app/hrm/designations': '/hrm/designations',
    '/app/hrm/holidays': '/hrm/holidays',
    '/app/hrm/office_Shift': '/hrm/office-shifts',
    '/app/assets/list': '/assets',
    '/app/assets/store': '/assets/create',
    '/app/assets/category': '/assets/categories',
    '/app/assets/dashboard': '/assets/dashboard',
    '/app/assets/assignments': '/assets/assignments',
    '/app/assets/maintenance': '/assets/maintenance',
    '/app/assets/transfers': '/assets/transfers',
    '/app/assets/depreciation': '/assets/depreciation',
    '/app/assets/reports': '/assets/reports',
    '/app/bookings/list': '/bookings',
    '/app/bookings/trays': '/bookings/trays',
    '/app/meeting/meetings': '/meetings',
    '/app/knowledge-base': '/kb',
    '/app/knowledge-base/groups': '/kb/groups',
    '/app/projects': '/projects',
    '/app/tasks': '/tasks',
    '/app/projects/dashboard': '/projects/dashboard',
    '/app/projects/milestones': '/projects/milestones',
    '/app/projects/timesheets': '/projects/timesheets',
    '/app/projects/reports': '/projects/reports',
    '/app/tasks/board': '/tasks/board',
    '/app/contracts': '/contracts',
    '/app/documents': '/documents',
    '/app/fleet/dashboard': '/fleet/dashboard',
    '/app/fleet/vehicles': '/fleet/vehicles',
    '/app/fleet/maintenance': '/fleet/maintenance',
    '/app/fleet/fuel-logs': '/fleet/fuel-logs',
    '/app/fleet/assignments': '/fleet/assignments',
    '/app/fleet/reports': '/fleet/reports',
    '/app/hospital/dashboard': '/hospital/dashboard',
    '/app/hospital/patients': '/hospital/patients',
    '/app/hospital/doctors': '/hospital/doctors',
    '/app/hospital/departments': '/hospital/departments',
    '/app/hospital/appointments': '/hospital/appointments',
    '/app/hospital/visits': '/hospital/visits',
    '/app/hospital/wards': '/hospital/wards',
    '/app/hospital/admissions': '/hospital/admissions',
    '/app/hospital/lab-tests': '/hospital/lab-tests',
    '/app/hospital/lab-orders': '/hospital/lab-orders',
    '/app/hospital/invoices': '/hospital/invoices',
    '/app/hospital/reports': '/hospital/reports',
    '/app/school/dashboard': '/school/dashboard',
    '/app/school/students': '/school/students',
    '/app/school/enrollments': '/school/enrollments',
    '/app/school/teachers': '/school/teachers',
    '/app/school/academics': '/school/academics',
    '/app/school/attendance': '/school/attendance',
    '/app/school/timetable': '/school/timetable',
    '/app/school/exams': '/school/exams',
    '/app/school/fees': '/school/fees',
    '/app/school/reports': '/school/reports',
    '/app/promotions': '/promotions',
    '/app/reports/analytics_report': '/reports/analytics',
    '/app/sales/store': '/sales/create',
    '/app/sales/list': '/sales',
    '/app/pos': '/pos',
    '/app/purchases/store': '/purchases/create',
    '/app/purchases/list': '/purchases',
    '/app/quotations/store': '/quotations/create',
    '/app/quotations/list': '/quotations',
    '/app/sale_return/list': '/sale-returns',
    '/app/purchase_return/list': '/purchase-returns',
    '/app/adjustments/store': '/adjustments/create',
    '/app/adjustments/list': '/adjustments',
    '/app/transfers/store': '/transfers/create',
    '/app/transfers/list': '/transfers',
    '/app/deposits/store': '/deposits/create',
    '/app/deposits/list': '/deposits',
    '/app/deposits/category': '/deposits/categories',
    '/app/hrm/employees': '/hrm/employees',
    '/app/hrm/attendance': '/hrm/attendance',
    '/app/hrm/leaves/list': '/hrm/leaves',
    '/app/hrm/leaves/type': '/hrm/leave-types',
    '/app/hrm/payrolls': '/hrm/payrolls',
    '/app/marketing/dashboard': '/marketing/dashboard',
    '/app/marketing/campaigns': '/marketing/campaigns',
    '/app/marketing/segments': '/marketing/segments',
    '/app/marketing/templates/sms': '/marketing/templates/sms',
    '/app/marketing/templates/whatsapp': '/marketing/templates/whatsapp',
    '/app/marketing/templates/email': '/marketing/templates/email',
    '/app/marketing/reports': '/marketing/reports',
    '/app/marketing/settings': '/marketing/settings',
};

export const MENU = [
    {
        key: 'dashboard',
        icon: 'bar-chart',
        label: 'dashboard',
        to: '/app/dashboard',
        permissions: [],
    },
    {
        key: 'Store',
        icon: 'shopping-bag',
        label: 'Store',
        permissions: ['Store_settings_view', 'Orders_view', 'Collections_view', 'Banners_view', 'Subscribers_view', 'Messages_view', 'Customers_view'],
        children: [
            { label: 'Visit_Online_Store', href: '/online_store', permissions: [] },
            { label: 'Settings', to: '/app/Store/Settings', permissions: ['Store_settings_view'] },
            { label: 'Payment_Gateway', to: '/app/Store/PaymentGateway', permissions: ['payment_gateway'] },
            { label: 'Online_Orders', to: '/app/Store/Orders', permissions: ['Orders_view'] },
            { label: 'Collections', to: '/app/Store/Collections', permissions: ['Collections_view'] },
            { label: 'Banners', to: '/app/Store/Banners', permissions: ['Banners_view'] },
            { label: 'Subscribers', to: '/app/Store/Subscribers', permissions: ['Subscribers_view'] },
            { label: 'Messages', to: '/app/Store/Messages', permissions: ['Messages_view'] },
            { label: 'Invite_Codes', to: '/app/Store/InviteCodes', permissions: ['Store_settings_view'] },
            { label: 'Pending_Customers', to: '/app/Store/PendingCustomers', permissions: ['Store_settings_view'] },
            { label: 'Customers_without_Login', to: '/app/People/Customers_without_ecommerce', permissions: ['Customers_view'] },
            { label: 'Customers_with_Login', to: '/app/People/Customers_ecommerce', permissions: ['Customers_view'] },
            { label: 'Shipping_Methods', to: '/app/Store/ShippingMethods', permissions: ['Store_settings_view'] },
            { label: 'Tax_Rates', to: '/app/Store/TaxRates', permissions: ['Store_settings_view'] },
            { label: 'Coupons', to: '/app/Store/Coupons', permissions: ['Store_settings_view'] },
            { label: 'Flash_Sales', to: '/app/Store/FlashSales', permissions: ['Store_settings_view'] },
            { label: 'Product_Reviews', to: '/app/Store/Reviews', permissions: ['Store_settings_view'] },
            { label: 'Popup_Messages', to: '/app/Store/Popups', permissions: ['Store_settings_view'] },
            { label: 'Quote_Requests', to: '/app/Store/QuoteRequests', permissions: ['Orders_view'] },
            { label: 'Returns_Requests', to: '/app/Store/Returns', permissions: ['Orders_view'] },
            { label: 'Pages', to: '/app/Store/Pages', permissions: ['Store_settings_view'] },
            { label: 'Menus', to: '/app/Store/Menus', permissions: ['Store_settings_view'] },
            {
                label: 'Real_Estate',
                permissions: ['realestate_properties', 'realestate_categories', 'realestate_inquiries'],
                children: [
                    { label: 'Properties', to: '/app/realestate/properties', permissions: ['realestate_properties'] },
                    { label: 'Property_Categories', to: '/app/realestate/categories', permissions: ['realestate_categories'] },
                    { label: 'Property_Inquiries', to: '/app/realestate/inquiries', permissions: ['realestate_inquiries'] },
                ],
            },
        ],
    },
    {
        key: 'People',
        icon: 'users',
        label: 'People',
        permissions: ['Customers_view', 'Suppliers_view', 'customers_import', 'Suppliers_import'],
        children: [
            { label: 'Customers', to: '/app/People/Customers', permissions: ['Customers_view'] },
            { label: 'Add', labelKeys: ['Add', 'Customer'], to: '/app/People/Customers/create', permissions: ['Customers_add'] },
            { label: 'Import_Customers', to: '/app/People/Customers_import', permissions: ['customers_import'] },
            { label: 'Client_Portal', href: '/portal', permissions: ['Customers_view'] },
            { label: 'Suppliers', to: '/app/People/Suppliers', permissions: ['Suppliers_view'] },
            { label: 'Add', labelKeys: ['Add', 'Supplier'], to: '/app/People/Suppliers/create', permissions: ['Suppliers_add'] },
            { label: 'Import_Suppliers', to: '/app/People/Suppliers_import', permissions: ['Suppliers_import'] },
        ],
    },
    {
        key: 'User_Management',
        icon: 'shield-check',
        label: 'User_Management',
        permissions: ['users_view', 'permissions_view'],
        children: [
            { label: 'Users', to: '/app/User_Management/Users', permissions: ['users_view'] },
            { label: 'GroupPermissions', to: '/app/User_Management/permissions', permissions: ['permissions_view'] },
        ],
    },
    {
        key: 'products',
        icon: 'library-big',
        label: 'Products',
        permissions: ['products_add', 'products_view', 'product_import', 'opening_stock_import', 'barcode_view', 'brand', 'unit', 'count_stock', 'category', 'subcategory'],
        children: [
            { label: 'AddProduct', to: '/app/products/store', permissions: ['products_add'] },
            { label: 'productsList', to: '/app/products/list', permissions: ['products_view'] },
            { label: 'import_products', to: '/app/products/import', permissions: ['product_import'] },
            { label: 'Import (Update Only)', to: '/app/products/import-update', permissions: ['product_import'] },
            { label: 'Opening_Stock', to: '/app/products/opening_stock_import', permissions: ['opening_stock_import'] },
            { label: 'Printbarcode', to: '/app/products/barcode', permissions: ['barcode_view'] },
            { label: 'CountStock', to: '/app/products/count_stock', permissions: ['count_stock'] },
            { label: 'Categories', to: '/app/products/Categories', permissions: ['category'] },
            { label: 'SubCategory', to: '/app/products/SubCategories', permissions: ['subcategory'] },
            { label: 'Brand', to: '/app/products/Brands', permissions: ['brand'] },
            { label: 'Size_Guides', to: '/app/products/SizeGuides', permissions: ['size_guides'] },
            { label: 'Units', to: '/app/products/Units', permissions: ['unit'] },
            { label: 'Vehicle Fitment', to: '/app/products/vehicle_fitment', permissions: ['products_view'] },
            { label: 'Batches', to: '/app/products/Batches', permissions: ['view_batches', 'batch_view'] },
            { label: 'Serial_Numbers', to: '/app/serial_numbers/list', permissions: ['serial_numbers'] },
        ],
    },
    {
        key: 'sales',
        icon: 'shopping-cart',
        label: 'Sales',
        permissions: ['Sales_view', 'Sales_add', 'Pos_view', 'customer_display_screen_setup', 'shipment', 'real_time_sales_counter'],
        children: [
            { label: 'ListSales', to: '/app/sales/list', permissions: ['Sales_view'] },
            { label: 'AddSale', to: '/app/sales/store', permissions: ['Sales_add'] },
            { label: 'Import_Sales', to: '/app/sales/import_sales', permissions: ['Sales_add'] },
            { label: 'POS', to: '/app/pos', permissions: ['Pos_view'] },
            { label: 'Customer_Screen', to: '/app/customer-display/setup', permissions: ['customer_display_screen_setup'] },
            { label: 'Shipments', to: '/app/sales/shipment', permissions: ['shipment'] },
            { label: 'Real_time_Sales_Counter', to: '/app/real-time-sales-counter', permissions: ['real_time_sales_counter'] },
            { label: 'KitchenDisplay', to: '/app/kitchen-display', permissions: ['kitchen_display_view'] },
        ],
    },
    {
        key: 'sale_return',
        icon: 'chevron-right',
        label: 'SalesReturn',
        to: '/app/sale_return/list',
        permissions: ['Sale_Returns_view'],
    },
    {
        key: 'purchases',
        icon: 'receipt',
        label: 'Purchases',
        permissions: ['Purchases_view', 'Purchases_add'],
        children: [
            { label: 'AddPurchase', to: '/app/purchases/store', permissions: ['Purchases_add'] },
            { label: 'ListPurchases', to: '/app/purchases/list', permissions: ['Purchases_view'] },
            { label: 'Import_Purchases', to: '/app/purchases/import_purchases', permissions: ['Purchases_add'] },
        ],
    },
    {
        key: 'purchase_return',
        icon: 'chevron-left',
        label: 'PurchasesReturn',
        to: '/app/purchase_return/list',
        permissions: ['Purchase_Returns_view'],
    },
    {
        key: 'quotations',
        icon: 'shopping-basket',
        label: 'Quotations',
        permissions: ['Quotations_view', 'Quotations_add'],
        children: [
            { label: 'AddQuote', to: '/app/quotations/store', permissions: ['Quotations_add'] },
            { label: 'ListQuotations', to: '/app/quotations/list', permissions: ['Quotations_view'] },
        ],
    },
    {
        key: 'adjustments',
        icon: 'map-pin',
        label: 'Stock Adjustment',
        permissions: ['adjustment_view', 'adjustment_add'],
        children: [
            { label: 'CreateAdjustment', to: '/app/adjustments/store', permissions: ['adjustment_add'] },
            { label: 'ListAdjustments', to: '/app/adjustments/list', permissions: ['adjustment_view'] },
        ],
    },
    {
        key: 'transfers',
        icon: 'arrow-left',
        label: 'Stock Transfers',
        permissions: ['transfer_view', 'transfer_add'],
        children: [
            { label: 'CreateTransfer', to: '/app/transfers/store', permissions: ['transfer_add'] },
            { label: 'ListTransfers', to: '/app/transfers/list', permissions: ['transfer_view'] },
        ],
    },
    {
        key: 'damages',
        icon: 'shopping-bag',
        label: 'Damages',
        permissions: ['damage_view'],
        children: [
            { label: 'Create_Damage', to: '/app/damages/store', permissions: ['damage_view'] },
            { label: 'Damages', to: '/app/damages/list', permissions: ['damage_view'] },
        ],
    },
    {
        key: 'hrm',
        icon: 'library',
        label: 'hrm',
        permissions: ['company', 'department', 'designation', 'office_shift', 'view_employee', 'attendance', 'leave', 'holiday', 'payroll', 'contracts', 'knowledge_base_view'],
        children: [
            { label: 'Company', to: '/app/hrm/company', permissions: ['company'] },
            { label: 'Departments', to: '/app/hrm/departments', permissions: ['department'] },
            { label: 'Designations', to: '/app/hrm/designations', permissions: ['designation'] },
            { label: 'Office_Shift', to: '/app/hrm/office_Shift', permissions: ['office_shift'] },
            { label: 'Employees', to: '/app/hrm/employees', permissions: ['view_employee'] },
            { label: 'Attendance', to: '/app/hrm/attendance', permissions: ['attendance'] },
            {
                label: 'Leave_request',
                permissions: ['leave'],
                children: [
                    { label: 'Leave_request', to: '/app/hrm/leaves/list', permissions: [] },
                    { label: 'Leave_type', to: '/app/hrm/leaves/type', permissions: [] },
                ],
            },
            { label: 'Holidays', to: '/app/hrm/holidays', permissions: ['holiday'] },
            { label: 'Payroll', to: '/app/hrm/payrolls', permissions: ['payroll'] },
            { label: 'Contracts', to: '/app/contracts', permissions: ['contracts'] },
            { label: 'Knowledge_Base', to: '/app/knowledge-base', permissions: ['knowledge_base_view'] },
            { label: 'Article Groups', to: '/app/knowledge-base/groups', permissions: ['knowledge_base_view'] },
        ],
    },
    {
        key: 'recruit',
        icon: 'users',
        label: 'Recruits and Jobs',
        permissions: ['recruit_job', 'recruit_category', 'recruit_candidate', 'recruit_application', 'recruit_interview'],
        children: [
            { label: 'Dashboard', to: '/app/recruit/dashboard', permissions: ['recruit_job'] },
            { label: 'Jobs', to: '/app/recruit/jobs', permissions: ['recruit_job'] },
            { label: 'Candidates', to: '/app/recruit/candidates', permissions: ['recruit_candidate'] },
            { label: 'Applications', to: '/app/recruit/applications', permissions: ['recruit_application'] },
            { label: 'Interviews', to: '/app/recruit/interviews', permissions: ['recruit_interview'] },
            { label: 'Job_Categories', to: '/app/recruit/categories', permissions: ['recruit_category'] },
            { label: 'Reports', to: '/app/recruit/reports', permissions: ['recruit_job'] },
        ],
    },
    {
        key: 'meeting',
        icon: 'calendar-days',
        label: 'Meetings',
        permissions: ['meeting', 'meeting_attendance', 'meeting_report'],
        children: [
            { label: 'Dashboard', to: '/app/meeting/dashboard', permissions: ['meeting'] },
            { label: 'Meetings', to: '/app/meeting/meetings', permissions: ['meeting'] },
            { label: 'Calendar', to: '/app/meeting/calendar', permissions: ['meeting'] },
            { label: 'Reports', to: '/app/meeting/reports', permissions: ['meeting_report'] },
        ],
    },
    {
        key: 'marketing',
        icon: 'megaphone',
        label: 'Marketing',
        permissions: ['marketing_dashboard', 'marketing_campaigns', 'marketing_segments', 'marketing_templates', 'marketing_reports', 'marketing_settings'],
        children: [
            { label: 'Dashboard', to: '/app/marketing/dashboard', permissions: ['marketing_dashboard'] },
            { label: 'Campaigns', to: '/app/marketing/campaigns', permissions: ['marketing_campaigns'] },
            { label: 'Customer_Segments', to: '/app/marketing/segments', permissions: ['marketing_segments'] },
            { label: 'SMS_Templates', to: '/app/marketing/templates/sms', permissions: ['marketing_templates'] },
            { label: 'WhatsApp_Templates', to: '/app/marketing/templates/whatsapp', permissions: ['marketing_templates'] },
            { label: 'Email_Templates', to: '/app/marketing/templates/email', permissions: ['marketing_templates'] },
            { label: 'Reports', to: '/app/marketing/reports', permissions: ['marketing_reports'] },
            { label: 'Marketing_Settings', to: '/app/marketing/settings', permissions: ['marketing_settings'] },
        ],
    },
    {
        key: 'accounting',
        icon: 'wallet',
        label: 'Accounting',
        permissions: ['expense_view', 'expense_add', 'deposit_view', 'deposit_add', 'account', 'transfer_money', 'accounting_dashboard', 'chart_of_accounts', 'journal_entries', 'trial_balance', 'accounting_profit_loss', 'balance_sheet', 'accounting_tax_report'],
        children: [
            { label: 'dashboard', to: '/app/accounting-v2/dashboard', permissions: ['accounting_dashboard'] },
            { label: 'Chart_of_Accounts_Title', to: '/app/accounting-v2/chart-of-accounts', permissions: ['chart_of_accounts'] },
            { label: 'Journal_Entries_Title', to: '/app/accounting-v2/journal-entries', permissions: ['journal_entries'] },
            { label: 'Trial_Balance_Title', to: '/app/accounting-v2/reports/trial-balance', permissions: ['trial_balance'] },
            { label: 'Profit_Loss_Title', to: '/app/accounting-v2/reports/profit-and-loss', permissions: ['accounting_profit_loss'] },
            { label: 'Balance_Sheet_Title', to: '/app/accounting-v2/reports/balance-sheet', permissions: ['balance_sheet'] },
            { label: 'Tax_Summary_Report', to: '/app/accounting-v2/reports/tax-report', permissions: ['accounting_tax_report'] },
            { label: 'List_accounts', to: '/app/accounts', permissions: ['account'] },
            { label: 'Transfers_Money', to: '/app/transfer_money', permissions: ['transfer_money'] },
            { label: 'Create_Expense', to: '/app/expenses/store', permissions: ['expense_add'] },
            { label: 'ListExpenses', to: '/app/expenses/list', permissions: ['expense_view'] },
            { label: 'Create_deposit', to: '/app/deposits/store', permissions: ['deposit_add'] },
            { label: 'List_Deposit', to: '/app/deposits/list', permissions: ['deposit_view'] },
            { label: 'Expense_Category', to: '/app/expenses/category', permissions: ['expense_view'] },
            { label: 'Deposit_Category', to: '/app/deposits/category', permissions: ['deposit_view'] },
        ],
    },
    {
        key: 'EWallet',
        icon: 'wallet',
        label: 'E_Wallet',
        permissions: ['ewallet'],
        children: [
            { label: 'E_Wallet_Dashboard', to: '/app/EWallet/Dashboard', permissions: [] },
            { label: 'Wallet_Items', to: '/app/EWallet/Items', permissions: [] },
            { label: 'E_Wallet_Settings', to: '/app/EWallet/Settings', permissions: [] },
        ],
    },
    {
        key: 'commissions',
        icon: 'wallet',
        label: 'Commissions',
        permissions: ['commissions_view'],
        children: [
            { label: 'Commission_Programs', to: '/app/commissions/programs', permissions: ['commissions_view'] },
            { label: 'Sales_Agents', to: '/app/commissions/agents', permissions: ['commissions_view'] },
            { label: 'Commission_Rules', to: '/app/commissions/rules', permissions: ['commissions_view'] },
            { label: 'Commission_Receipts', to: '/app/commissions/receipts', permissions: ['commissions_view'] },
            { label: 'Commission_Report', to: '/app/commissions/report', permissions: ['commissions_view'] },
        ],
    },
    {
        key: 'promotions',
        icon: 'percent',
        label: 'Promotions',
        to: '/app/promotions',
        permissions: ['promotion'],
    },
    {
        key: 'woocommerce_settings',
        icon: 'shopping-cart',
        label: 'WooCommerce',
        to: '/app/woocommerce',
        permissions: ['woocommerce_settings'],
    },
    {
        key: 'shopify',
        icon: 'shopping-cart',
        label: 'Shopify',
        permissions: ['shopify_stores', 'shopify_sync', 'shopify_logs'],
        children: [
            { label: 'Dashboard', to: '/app/shopify/dashboard', permissions: ['shopify_stores'] },
            { label: 'Stores', to: '/app/shopify/stores', permissions: ['shopify_stores'] },
            { label: 'Sync Centre', to: '/app/shopify/sync', permissions: ['shopify_sync'] },
            { label: 'Mappings', to: '/app/shopify/mappings', permissions: ['shopify_sync'] },
            { label: 'Logs', to: '/app/shopify/logs', permissions: ['shopify_logs'] },
        ],
    },
    {
        key: 'documents',
        icon: 'folder-archive',
        label: 'Document Archive',
        to: '/app/documents',
        permissions: ['documents_view'],
    },
    {
        key: 'subscription_product',
        icon: 'dollar-sign',
        label: 'Subscription_Product',
        to: '/app/subscription_product/list',
        permissions: ['subscription_product'],
    },
    {
        key: 'manufacturing',
        icon: 'settings',
        label: 'Manufacturing (MRP)',
        permissions: ['mrp_boms', 'mrp_production', 'mrp_quality', 'mrp_planning', 'mrp_reports'],
        children: [
            { label: 'Dashboard', to: '/app/mrp/dashboard', permissions: ['mrp_production'] },
            { label: 'Production Orders', to: '/app/mrp/production-orders', permissions: ['mrp_production'] },
            { label: 'Shop Floor', to: '/app/mrp/work-orders', permissions: ['mrp_production'] },
            { label: 'Bills of Materials', to: '/app/mrp/boms', permissions: ['mrp_boms'] },
            { label: 'Work Centres', to: '/app/mrp/work-centers', permissions: ['mrp_boms'] },
            { label: 'Quality Control', to: '/app/mrp/quality', permissions: ['mrp_quality'] },
            { label: 'Planning', to: '/app/mrp/planning', permissions: ['mrp_planning'] },
            { label: 'Reports', to: '/app/mrp/reports', permissions: ['mrp_reports'] },
        ],
    },
    {
        key: 'assets',
        icon: 'settings',
        label: 'Asset Management',
        permissions: ['assets', 'asset_assignments', 'asset_maintenance', 'asset_transfers', 'asset_reports'],
        children: [
            { label: 'Dashboard', to: '/app/assets/dashboard', permissions: ['assets'] },
            { label: 'Add_Asset', to: '/app/assets/store', permissions: ['assets'] },
            { label: 'Assets_List', to: '/app/assets/list', permissions: ['assets'] },
            { label: 'Assignments', to: '/app/assets/assignments', permissions: ['asset_assignments'] },
            { label: 'Maintenance', to: '/app/assets/maintenance', permissions: ['asset_maintenance'] },
            { label: 'Transfers', to: '/app/assets/transfers', permissions: ['asset_transfers'] },
            { label: 'Depreciation', to: '/app/assets/depreciation', permissions: ['asset_reports'] },
            { label: 'Due_Assets', to: '/app/assets/due', permissions: ['assets'] },
            { label: 'Asset_Category', to: '/app/assets/category', permissions: ['assets'] },
            { label: 'Asset Reports', to: '/app/assets/reports', permissions: ['asset_reports'] },
        ],
    },
    {
        key: 'projects',
        icon: 'archive',
        label: 'Projects Management',
        permissions: ['projects', 'tasks', 'project_milestones', 'project_timesheets', 'project_reports'],
        children: [
            { label: 'Dashboard', to: '/app/projects/dashboard', permissions: ['projects'] },
            { label: 'Projects', to: '/app/projects', permissions: ['projects'] },
            { label: 'Tasks', to: '/app/tasks', permissions: ['tasks'] },
            { label: 'Task Board', to: '/app/tasks/board', permissions: ['tasks'] },
            { label: 'Milestones', to: '/app/projects/milestones', permissions: ['project_milestones'] },
            { label: 'Timesheets', to: '/app/projects/timesheets', permissions: ['project_timesheets'] },
            { label: 'Project Reports', to: '/app/projects/reports', permissions: ['project_reports'] },
        ],
    },
    {
        key: 'bookings',
        icon: 'calendar-days',
        label: 'Booking Management',
        permissions: ['bookings'],
        children: [
            { label: 'Booking_List', to: '/app/bookings/list', permissions: ['bookings'] },
            { label: 'Calendar_View', to: '/app/bookings/calendar', permissions: ['bookings'] },
            { label: 'Trays', to: '/app/bookings/trays', permissions: ['trays'] },
        ],
    },
    {
        key: 'service',
        icon: 'wrench',
        label: 'Service_Maintenance',
        permissions: ['service_jobs'],
        children: [
            { label: 'Service_Jobs', to: '/app/service/jobs', permissions: [] },
            { label: 'Awaiting_Approval', to: '/app/service/jobs?status=quoted', permissions: [] },
            { label: 'Ready_For_Pickup', to: '/app/service/jobs?status=ready', permissions: [] },
            { label: 'Awaiting_Payment', to: '/app/service/jobs?payment_status=unpaid', permissions: [] },
            { label: 'Service_Technicians', to: '/app/service/technicians', permissions: [] },
            { label: 'Checklist_Categories', to: '/app/service/checklist-categories', permissions: [] },
            { label: 'Checklist_Items', to: '/app/service/checklists', permissions: [] },
            { label: 'Maintenance_History', to: '/app/service/history', permissions: [] },
        ],
    },
    {
        key: 'fleet',
        icon: 'truck',
        label: 'Fleet Management',
        permissions: ['fleet_vehicles_view', 'fleet_maintenance', 'fleet_fuel', 'fleet_assignments', 'fleet_reports'],
        children: [
            { label: 'Dashboard', to: '/app/fleet/dashboard', permissions: ['fleet_vehicles_view'] },
            { label: 'Vehicles', to: '/app/fleet/vehicles', permissions: ['fleet_vehicles_view'] },
            { label: 'Maintenance', to: '/app/fleet/maintenance', permissions: ['fleet_maintenance'] },
            { label: 'Fuel Logs', to: '/app/fleet/fuel-logs', permissions: ['fleet_fuel'] },
            { label: 'Assignments', to: '/app/fleet/assignments', permissions: ['fleet_assignments'] },
            { label: 'Fleet Reports', to: '/app/fleet/reports', permissions: ['fleet_reports'] },
        ],
    },
    {
        key: 'hospital',
        icon: 'heart-pulse',
        label: 'Hospital Management',
        permissions: [
            'hms_dashboard', 'hms_patients_view', 'hms_doctors', 'hms_departments',
            'hms_appointments', 'hms_visits', 'hms_admissions', 'hms_wards',
            'hms_lab', 'hms_billing', 'hms_reports',
        ],
        children: [
            { label: 'Dashboard', to: '/app/hospital/dashboard', permissions: ['hms_dashboard'] },
            { label: 'Patients', to: '/app/hospital/patients', permissions: ['hms_patients_view'] },
            { label: 'Appointments', to: '/app/hospital/appointments', permissions: ['hms_appointments'] },
            { label: 'Consultations', to: '/app/hospital/visits', permissions: ['hms_visits'] },
            { label: 'Admissions', to: '/app/hospital/admissions', permissions: ['hms_admissions'] },
            { label: 'Wards & Beds', to: '/app/hospital/wards', permissions: ['hms_wards'] },
            {
                label: 'Laboratory',
                permissions: ['hms_lab'],
                children: [
                    { label: 'Lab Orders', to: '/app/hospital/lab-orders', permissions: ['hms_lab'] },
                    { label: 'Test Catalogue', to: '/app/hospital/lab-tests', permissions: ['hms_lab'] },
                ],
            },
            { label: 'Billing', to: '/app/hospital/invoices', permissions: ['hms_billing'] },
            { label: 'Doctors', to: '/app/hospital/doctors', permissions: ['hms_doctors'] },
            { label: 'Departments', to: '/app/hospital/departments', permissions: ['hms_departments'] },
            { label: 'Hospital Reports', to: '/app/hospital/reports', permissions: ['hms_reports'] },
        ],
    },
    {
        key: 'school',
        icon: 'graduation-cap',
        label: 'School Management',
        permissions: [
            'school_dashboard', 'school_students_view', 'school_teachers', 'school_academics',
            'school_enrollment', 'school_attendance', 'school_exams', 'school_timetable',
            'school_fees', 'school_reports',
        ],
        children: [
            { label: 'Dashboard', to: '/app/school/dashboard', permissions: ['school_dashboard'] },
            { label: 'Students', to: '/app/school/students', permissions: ['school_students_view'] },
            { label: 'Enrolment', to: '/app/school/enrollments', permissions: ['school_enrollment'] },
            { label: 'Attendance', to: '/app/school/attendance', permissions: ['school_attendance'] },
            { label: 'Timetable', to: '/app/school/timetable', permissions: ['school_timetable'] },
            { label: 'Exams & Results', to: '/app/school/exams', permissions: ['school_exams'] },
            { label: 'Fees', to: '/app/school/fees', permissions: ['school_fees'] },
            { label: 'Teachers', to: '/app/school/teachers', permissions: ['school_teachers'] },
            { label: 'Academic Setup', to: '/app/school/academics', permissions: ['school_academics'] },
            { label: 'School Reports', to: '/app/school/reports', permissions: ['school_reports'] },
        ],
    },
    {
        key: 'settings',
        icon: 'database-zap',
        label: 'Settings',
        permissions: ['setting_system', 'business_modules', 'update_settings', 'sms_settings', 'quickbooks_settings', 'notification_template', 'pos_settings', 'appearance_settings', 'translations_settings', 'payment_gateway', 'mail_settings', 'warehouse', 'warehouse_locations', 'backup', 'payment_methods', 'currency', 'login_device_management', 'system_health_view', 'webhooks_view'],
        children: [
            { label: 'SystemSettings', to: '/app/settings/System_settings', permissions: ['setting_system'] },
            { label: 'Warehouses', to: '/app/settings/Warehouses', permissions: ['warehouse'] },
            { label: 'Modules', to: '/app/settings/business_modules', permissions: ['business_modules', 'setting_system'] },
            { label: 'Quickbooks_Sync', to: '/app/settings/quickbooks_sync', permissions: ['quickbooks_settings'] },
            { label: 'Dynamic_Appearance', to: '/app/settings/appearance_settings', permissions: ['appearance_settings'] },
            { label: 'Languages', to: '/app/settings/translations_settings', permissions: ['translations_settings'] },
            { label: 'Payment_Methods', to: '/app/settings/payment_methods', permissions: ['payment_methods'] },
            { label: 'sms_settings', to: '/app/settings/sms_settings', permissions: ['sms_settings'] },
            { label: 'sms_templates', to: '/app/settings/sms_templates', permissions: ['notification_template'] },
            { label: 'mail_settings', to: '/app/settings/mail_settings', permissions: ['mail_settings'] },
            { label: 'email_templates', to: '/app/settings/email_templates', permissions: ['notification_template'] },
            { label: 'Pos_Settings', to: '/app/settings/pos_settings', permissions: ['pos_settings'] },
            { label: 'POS_Receipt', to: '/app/settings/pos_receipt', permissions: ['pos_settings'] },
            { label: 'update_settings', to: '/app/settings/update_settings', permissions: ['update_settings'] },
            { label: 'Payment_Gateway', to: '/app/settings/payment_gateway', permissions: ['payment_gateway'] },
            { label: 'Currencies', to: '/app/settings/Currencies', permissions: ['currency'] },
            { label: 'Backup', to: '/app/settings/Backup', permissions: ['backup'] },
            { label: 'System_Health', to: '/app/settings/system_health', permissions: ['system_health_view'] },
            { label: 'Webhooks', to: '/app/settings/webhooks', permissions: ['webhooks_view'] },
            { label: 'Login_Device_Management', to: '/app/settings/login_devices', permissions: ['login_device_management'] },
            { label: 'Loyalty_Rewards', to: '/app/loyalty/rewards', permissions: ['loyalty_rewards'] },
        ],
    },
    {
        key: 'reports',
        icon: 'trending-up',
        label: 'Reports',
        permissions: ['Reports_payments_Sales', 'Reports_payments_Purchases', 'Reports_payments_Sale_Returns', 'Reports_payments_purchase_Return', 'Warehouse_report', 'Reports_profit', 'analytics_report', 'Stock_Inventory_Valuation', 'inventory_valuation', 'expenses_report', 'deposits_report', 'Reports_purchase', 'Reports_quantity_alerts', 'Reports_sales', 'product_sales_report', 'product_purchases_report', 'Reports_suppliers', 'Top_Suppliers_Report', 'Reports_customers', 'Top_products', 'inactive_customers_report', 'Top_customers', 'report_device_management', 'users_report', 'product_report', 'zeroSalesProducts', 'Dead_Stock_Report', 'expiry_report', 'Stock_Aging_Report', 'Stock_Transfer_Report', 'discount_summary_report', 'Stock_Adjustment_Report', 'customer_loyalty_points_report', 'tax_summary_report', 'draft_invoices_report', 'report_transactions', 'cash_flow_report', 'report_attendance_summary', 'seller_report', 'report_sales_by_category', 'report_sales_by_brand', 'report_error_logs', 'cash_register_report', 'report_warranty', 'stock_report', 'internal_location_report', 'negative_stock_report', 'return_ratio_report', 'service_jobs', 'service_jobs_report', 'checklist_completion_report', 'customer_maintenance_history_report', 'sales_3d_dashboard', 'AI_Reports'],
        children: [
            { label: 'AI_Reports', icon: 'lightbulb', to: '/app/reports/ai_reports', permissions: ['AI_Reports'] },
            { label: 'sales_3d_dashboard', to: '/app/reports/sales-3d-dashboard', permissions: ['sales_3d_dashboard'] },
            {
                label: 'Payments',
                permissions: ['Reports_payments_Purchases', 'Reports_payments_Sales', 'Reports_payments_Sale_Returns', 'Reports_payments_purchase_Return'],
                children: [
                    { label: 'Purchases', to: '/app/reports/payments_purchase', permissions: ['Reports_payments_Purchases'] },
                    { label: 'Sales', to: '/app/reports/payments_sale', permissions: ['Reports_payments_Sales'] },
                    { label: 'SalesReturn', to: '/app/reports/payments_sales_returns', permissions: ['Reports_payments_Sale_Returns'] },
                    { label: 'PurchasesReturn', to: '/app/reports/payments_purchases_returns', permissions: ['Reports_payments_purchase_Return'] },
                ],
            },
            {
                label: 'Profit Reports',
                icon: 'dollar-sign',
                permissions: ['Reports_profit'],
                children: [
                    { label: 'Profit by Product', to: '/app/reports/profit/product', permissions: ['Reports_profit'] },
                    { label: 'Profit by Category', to: '/app/reports/profit/category', permissions: ['Reports_profit'] },
                    { label: 'Profit by Unit', to: '/app/reports/profit/unit', permissions: ['Reports_profit'] },
                    { label: 'Profit by Customer', to: '/app/reports/profit/customer', permissions: ['Reports_profit'] },
                    { label: 'Profit by Date', to: '/app/reports/profit/date', permissions: ['Reports_profit'] },
                    { label: 'Profit by Warehouse', to: '/app/reports/profit/warehouse', permissions: ['Reports_profit'] },
                ],
            },
            { label: 'ProfitandLoss', to: '/app/reports/profit_and_loss', permissions: ['Reports_profit'] },
            { label: 'Report_Transactions', to: '/app/reports/report_transactions', permissions: ['report_transactions'] },
            { label: 'Cash_Flow_Report', to: '/app/reports/cash_flow_report', permissions: ['cash_flow_report'] },
            { label: 'Seller_report', to: '/app/reports/seller_report', permissions: ['seller_report'] },
            { label: 'attendance_summary', to: '/app/reports/attendance_report', permissions: ['report_attendance_summary'] },
            { label: 'Analytics_Report', to: '/app/reports/analytics_report', permissions: ['analytics_report'] },
            { label: 'Stock_Inventory_Valuation', to: '/app/reports/stock_inventory_valuation', permissions: ['Stock_Inventory_Valuation'] },
            { label: 'Cash_Register_Report', to: '/app/reports/cash-registers', permissions: ['cash_register_report'] },
            { label: 'Warranty_Guarantee_Report', to: '/app/reports/warranty_guarantee_report', permissions: ['report_warranty'] },
            { label: 'Inventory_Valuation', to: '/app/reports/inventory_valuation_summary', permissions: ['inventory_valuation'] },
            { label: 'Expense_Report', to: '/app/reports/expenses_report', permissions: ['expenses_report'] },
            { label: 'Deposits_Report', to: '/app/reports/deposits_report', permissions: ['deposits_report'] },
            { label: 'ProductQuantityAlerts', to: '/app/reports/quantity_alerts', permissions: ['Reports_quantity_alerts'] },
            { label: 'Warehouse_report', to: '/app/reports/warehouse_report', permissions: ['Warehouse_report'] },
            { label: 'Internal_Location_Report', to: '/app/reports/internal_location_report', permissions: ['internal_location_report'] },
            { label: 'stock_report', to: '/app/reports/stock_report', permissions: ['stock_report'] },
            { label: 'Available_Serial_Numbers', to: '/app/reports/serial_available_report', permissions: ['serial_numbers_report'] },
            { label: 'Sold_Serial_Numbers', to: '/app/reports/serial_sold_report', permissions: ['serial_numbers_report'] },
            { label: 'Serial_Movement_Log', to: '/app/reports/serial_movement_report', permissions: ['serial_numbers_report'] },
            { label: 'Product_Serial_Inventory', to: '/app/reports/serial_inventory_report', permissions: ['serial_numbers_report'] },
            { label: 'Negative_Stock_Report', to: '/app/reports/negative_stock_report', permissions: ['negative_stock_report'] },
            { label: 'product_report', to: '/app/reports/product_report', permissions: ['product_report'] },
            { label: 'Zero_Sales_Products_Report', to: '/app/reports/zero_sales_products_report', permissions: ['zeroSalesProducts'] },
            { label: 'Dead_Stock_Report', to: '/app/reports/dead_stock_report', permissions: ['Dead_Stock_Report'] },
            { label: 'Expiry_Report', to: '/app/reports/expiry_report', permissions: ['expiry_report'] },
            { label: 'Batch_Register_Report', to: '/app/reports/batch_register_report', permissions: ['Batch_Register_Report'] },
            { label: 'Stock_Aging_Report', to: '/app/reports/stock_aging_report', permissions: ['Stock_Aging_Report'] },
            { label: 'Stock_Transfer_Report', to: '/app/reports/stock_transfer_report', permissions: ['Stock_Transfer_Report'] },
            { label: 'Stock_Adjustment_Report', to: '/app/reports/stock_adjustment_report', permissions: ['Stock_Adjustment_Report'] },
            { label: 'Discount_Summary_Report', to: '/app/reports/discount_summary_report', permissions: ['discount_summary_report'] },
            { label: 'Customer_Loyalty_Points_Report', to: '/app/reports/customer_loyalty_points_report', permissions: ['customer_loyalty_points_report'] },
            { label: 'Tax_Summary_Report', to: '/app/reports/tax_summary_report', permissions: ['tax_summary_report'] },
            { label: 'Draft_Invoices_Report', to: '/app/reports/draft_invoices_report', permissions: ['draft_invoices_report'] },
            { label: 'Return_Ratio_Report', to: '/app/reports/return_ratio_report', permissions: ['return_ratio_report'] },
            { label: 'SalesReport', to: '/app/reports/sales_report', permissions: ['Reports_sales'] },
            { label: 'product_sales_report', to: '/app/reports/product_sales_report', permissions: ['product_sales_report'] },
            { label: 'Sales_by_Category', to: '/app/reports/report_sales_by_category', permissions: ['report_sales_by_category'] },
            { label: 'Sales_by_Brand', to: '/app/reports/report_sales_by_brand', permissions: ['report_sales_by_brand'] },
            { label: 'PurchasesReport', to: '/app/reports/purchase_report', permissions: ['Reports_purchase'] },
            { label: 'Product_purchases_report', to: '/app/reports/product_purchases_report', permissions: ['product_purchases_report'] },
            { label: 'CustomersReport', to: '/app/reports/customers_report', permissions: ['Reports_customers'] },
            { label: 'Inactive_Customers_Report', to: '/app/reports/inactive_customers', permissions: ['inactive_customers_report'] },
            { label: 'Top_Suppliers_Report', to: '/app/reports/top_suppliers_report', permissions: ['Top_Suppliers_Report'] },
            { label: 'SuppliersReport', to: '/app/reports/providers_report', permissions: ['Reports_suppliers'] },
            { label: 'Top_Selling_Products', to: '/app/reports/top_selling_products', permissions: ['Top_products'] },
            { label: 'Top_customers', to: '/app/reports/top_customers', permissions: ['Top_customers'] },
            { label: 'Users_Report', to: '/app/reports/users_report', permissions: ['users_report'] },
            { label: 'Login_Activity_Report', to: '/app/reports/login_activity_report', permissions: ['report_device_management'] },
            { label: 'Error_Logs', to: '/app/reports/report_error_logs', permissions: ['report_error_logs'] },
            { label: 'Service_Jobs_Report', to: '/app/reports/service_jobs_report', permissions: ['service_jobs_report'] },
            { label: 'Checklist_Completion_Report', to: '/app/reports/checklist_completion_report', permissions: ['checklist_completion_report'] },
            { label: 'Customer_Maintenance_History_Report', to: '/app/reports/customer_maintenance_history_report', permissions: ['customer_maintenance_history_report'] },
        ],
    },
];

/** Where a legacy sidebar path should actually go. */
export function resolveTarget(to) {
    if (!to) return null;
    const next = MIGRATED_ROUTES[to];
    return next ? { type: 'next', path: next } : { type: 'legacy', path: `/#${to}` };
}
